spring:
  application:
    name: agendixdb
  datasource:
    url: jdbc:postgresql://localhost:5432/agendixdb
    username: postgres
    password: postgres
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
server:
  servlet: 
    context-path: /api
  port: 8080

flyway:
  url: jdbc:postgresql://localhost:5432/agendixdb
  schemas: agendixdb
  user: postgres
  password: itix.123